import NavBar from "@/components/NavBar/NavBar";
import { Inter } from "next/font/google";
import TabsSeccion from "./Component/TabsSeccion";
import SectionOutlet from "@/components/SectionOutlet";
import BackgroundDorm from "@/components/BackgroundDorm";
import CabeceraContenedor from "@/components/CabeceraContenedor";
import FormularioPrimerosLink from "./FormularioPrimerosLink";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function SeccionLayout({ children }) {
  return (
    <SectionOutlet>
      <div className="flex flex-col w-full mt-10 md:mt-0 gap-10">
        <BackgroundDorm>
          <CabeceraContenedor>
            <h2 className="text-blueGray-700 text-xl font-bold">
              Secciones a integrar en tu Tarjeta
            </h2>
          </CabeceraContenedor>
          <div className="flex-auto md:px-4 lg:px-4  pt-0">
            <form className="py-10 flex flex-col item-centar justify-between">
              <TabsSeccion />
              <div>{children}</div>
            </form>
          </div>
        </BackgroundDorm>
      </div>
    </SectionOutlet>
  );
}
